from .CriptomoedasView import CriptomoedasView
from .ExcluirContaView import ExcluirContaView
from .TabelaAcoesView import TabelaAcoesView
from .GraficosView import GraficosView
from .PerfilView import PerfilView
from .RegistroEtapa1View import RegistroEtapa1View
from .RegistroEtapa2View import RegistroEtapa2View
from .MudarSenhaView import MudarSenhaView
from .LoginView import LoginView
from .LogoutView import LogoutView
from .InfoPerfilEndividadoView import InfoPerfilEndividadoView
from .InfoPerfilInvestidorView import InfoPerfilInvestidorView
from .VisaoGeralView import VisaoGeralView
