# Generated by Django 5.1.4 on 2024-12-31 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_perfil', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=45)),
                ('ultimo_nome', models.CharField(max_length=45)),
                ('nome_usuario', models.CharField(max_length=45, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('perfil', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppFinVest.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='InfoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('divida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patrimonio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_financeira', to='AppFinVest.usuario')),
            ],
        ),
    ]
