# Generated by Django 5.1.4 on 2025-01-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0002_infofinanceira_mes_referente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_perfil',
            field=models.CharField(default='Investidor', max_length=45),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PerfilFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_perfil', models.CharField(max_length=45)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('divida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patrimonio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referente', models.CharField(max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_financeira', to='AppFinVest.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='InfoFinanceira',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
