# Generated by Django 5.1.4 on 2025-01-07 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0003_remove_usuario_perfil_usuario_tipo_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ativo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('preco_atual', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='perfilfinanceiro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='AppFinVest.usuario'),
        ),
        migrations.CreateModel(
            name='TabelaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativos', models.ManyToManyField(to='AppFinVest.precoativo')),
            ],
        ),
    ]
