# Generated by Django 5.1.4 on 2025-01-07 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0004_precoativo_alter_perfilfinanceiro_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precoativo',
            name='tipo',
            field=models.CharField(choices=[('Ação', 'Ação'), ('Criptomoeda', 'Criptomoeda')], max_length=50),
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='AppFinVest.precoativo')),
            ],
        ),
    ]
