# Generated by Django 5.1.4 on 2025-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0005_alter_precoativo_tipo_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='precoativo',
            name='capitalizacao_mercado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precoativo',
            name='volume_24h',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
