# Generated by Django 5.1.4 on 2025-01-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0006_precoativo_capitalizacao_mercado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precoativo',
            name='abertura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precoativo',
            name='fechamento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precoativo',
            name='maximo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precoativo',
            name='minimo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precoativo',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
