# Generated by Django 5.1.4 on 2025-01-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0007_precoativo_abertura_precoativo_fechamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precoativo',
            name='data',
            field=models.DateField(default='2025-01-08'),
            preserve_default=False,
        ),
    ]
