# Generated by Django 5.1.4 on 2025-01-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0009_alter_precoativo_preco_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='sla123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
