# Generated by Django 5.1.4 on 2025-01-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0010_usuario_email_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='sla123', max_length=128, verbose_name='senha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
