# Generated by Django 5.1.4 on 2025-01-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0012_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precoativo',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
