# Generated by Django 5.1.4 on 2025-01-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0013_alter_precoativo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilfinanceiro',
            name='divida',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='perfilfinanceiro',
            name='patrimonio',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='perfilfinanceiro',
            name='renda',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
