# Generated by Django 5.1.5 on 2025-01-18 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinVest', '0014_alter_perfilfinanceiro_divida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_meta', models.CharField(max_length=100)),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_meta', models.DateField()),
                ('atingida', models.BooleanField(default=False)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('automatica', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='AppFinVest.usuario')),
            ],
        ),
    ]
